/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author Cristian Padilla
 */

public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_result = new javax.swing.JTextField();
        btn_mm = new javax.swing.JButton();
        btn_retro = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_digit1 = new javax.swing.JButton();
        btn_digit2 = new javax.swing.JButton();
        btn_digit3 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_digit4 = new javax.swing.JButton();
        btn_digit5 = new javax.swing.JButton();
        btn_digit6 = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_digit7 = new javax.swing.JButton();
        btn_digit8 = new javax.swing.JButton();
        btn_digit9 = new javax.swing.JButton();
        btn_por = new javax.swing.JButton();
        btn_digit0 = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_opt = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_result.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        txt_result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultActionPerformed(evt);
            }
        });
        getContentPane().add(txt_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 90));

        btn_mm.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_mm.setText("±");
        btn_mm.setToolTipText("");
        btn_mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mmActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 76, 80));

        btn_retro.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_retro.setText("←");
        btn_retro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_retro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 76, 80));

        btn_ce.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_ce.setText("CE");
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 76, 80));

        btn_c.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_c.setText("C");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 76, 80));

        btn_digit1.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit1.setText("1");
        btn_digit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 76, 80));

        btn_digit2.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit2.setText("2");
        btn_digit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 76, 80));

        btn_digit3.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit3.setText("3");
        btn_digit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 76, 80));

        btn_mas.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_mas.setText("+");
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 76, 80));

        btn_digit4.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit4.setText("4");
        btn_digit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 76, 80));

        btn_digit5.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit5.setText("5");
        btn_digit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 76, 80));

        btn_digit6.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit6.setText("6");
        btn_digit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 76, 80));

        btn_menos.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 76, 80));

        btn_digit7.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit7.setText("7");
        btn_digit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 76, 80));

        btn_digit8.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit8.setText("8");
        btn_digit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 76, 80));

        btn_digit9.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit9.setText("9");
        btn_digit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 76, 80));

        btn_por.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_por.setText("*");
        btn_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porActionPerformed(evt);
            }
        });
        getContentPane().add(btn_por, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 76, 80));

        btn_digit0.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_digit0.setText("0");
        btn_digit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_digit0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_digit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 76, 80));

        btn_dot.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 76, 80));

        btn_igual.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 76, 80));

        btn_div.setFont(new java.awt.Font("Cambria Math", 1, 32)); // NOI18N
        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });
        getContentPane().add(btn_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 76, 80));

        menu_opt.setText("Opciones");
        menu_opt.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_opt.add(jMenuItem1);

        jMenuItem2.setText("Historial");
        menu_opt.add(jMenuItem2);

        jMenuBar1.add(menu_opt);

        menu_help.setText("Ayuda");
        menu_help.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jMenuBar1.add(menu_help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q){
        String Nums = txt_result.getText() + q;
        txt_result.setText(Nums);
    }
            
    
    private void txt_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultActionPerformed

    private void btn_digit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_btn_digit6ActionPerformed

    private void btn_digit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_btn_digit8ActionPerformed

    private void btn_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porActionPerformed
        NumEnter1 = Double.parseDouble(txt_result.getText() );
        txt_result.setText("");
        op = "*";
    }//GEN-LAST:event_btn_porActionPerformed

    private void btn_digit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_btn_digit1ActionPerformed

    private void btn_digit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_btn_digit2ActionPerformed

    private void btn_digit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_btn_digit3ActionPerformed

    private void btn_digit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_btn_digit4ActionPerformed

    private void btn_digit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_btn_digit5ActionPerformed

    private void btn_digit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit7ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_btn_digit7ActionPerformed

    private void btn_digit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_btn_digit9ActionPerformed

    private void btn_digit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_digit0ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_btn_digit0ActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(txt_result.getText() );
        txt_result.setText("");
        op = "/";
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        NumEnter1 = Double.parseDouble(txt_result.getText() );
        txt_result.setText("");
        op = "+";
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        NumEnter1 = Double.parseDouble(txt_result.getText() );
        txt_result.setText("");
        op = "-";
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txt_result.setText("");
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
        txt_result.setText("");
        
        String Fn, Sn;
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn =""; 
        Sn ="";
    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mmActionPerformed
        
        double nums = Double.parseDouble(String.valueOf(txt_result.getText()));
        nums = nums * (-1);
        txt_result.setText(String.valueOf(nums));
    }//GEN-LAST:event_btn_mmActionPerformed

    private void btn_retroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retroActionPerformed
        
        String retro = null;
        if (txt_result.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(txt_result.getText());
            sb.deleteCharAt(txt_result.getText().length() - 1);
            retro = sb.toString();
            txt_result.setText(retro);
        }
    }//GEN-LAST:event_btn_retroActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        
        if (! txt_result.getText().contains("."))
        {
            txt_result.setText(txt_result.getText() + btn_dot.getText());
        }
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        
        NumEnter2 = Double.parseDouble(txt_result.getText());
        
        if (op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            txt_result.setText(String.valueOf(Result));
        }
        
        else if (op == "-")
        {
            Result = NumEnter1 - NumEnter2;
            txt_result.setText(String.valueOf(Result));
        }
        
        else if (op == "*")
        {
            Result = NumEnter1 * NumEnter2;
            txt_result.setText(String.valueOf(Result));
        }
        
        else if (op == "/")
        {
            Result = NumEnter1 / NumEnter2;
            txt_result.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_digit0;
    private javax.swing.JButton btn_digit1;
    private javax.swing.JButton btn_digit2;
    private javax.swing.JButton btn_digit3;
    private javax.swing.JButton btn_digit4;
    private javax.swing.JButton btn_digit5;
    private javax.swing.JButton btn_digit6;
    private javax.swing.JButton btn_digit7;
    private javax.swing.JButton btn_digit8;
    private javax.swing.JButton btn_digit9;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_mm;
    private javax.swing.JButton btn_por;
    private javax.swing.JButton btn_retro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenu menu_opt;
    private javax.swing.JTextField txt_result;
    // End of variables declaration//GEN-END:variables
}
